project_id = "fwytxapogblcesvyxrzt"

[functions.pandavideo]
verify_jwt = false

[functions.sync-pandavideo-lessons]
verify_jwt = false

[functions.pagarme]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.hotmart-access]
verify_jwt = false