
INSERT INTO public.lead_forms (name, slug, description, fields, redirect_url, is_active) VALUES
('Campo Visual', 'campo-visual', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000001', true),
('Ciclofotocoagulação a Laser', 'ciclofotocoagulacao-a-laser', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000003', true),
('Degeneração Macular Relacionada a Idade', 'degeneracao-macular-relacionada-a-idade', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000011', true),
('Edema Macular Diabético', 'edema-macular-diabetico', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000010', true),
('Glaucoma Learning Experience 2.0', 'glaucoma-learning-experience-2.0', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000005', true),
('Introdução ao Glaucoma', 'introducao-ao-glaucoma', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000006', true),
('Propedêutica da Retina', 'propedeutica-da-retina', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000009', true),
('Retinopatia da Prematuridade', 'retinopatia-da-prematuridade', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000008', true),
('SLT', 'slt', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000007', true),
('ThinkTank do Glaucoma Instituto', 'thinktank-do-glaucoma-instituto', NULL, '[{"name":"name","label":"Nome","type":"text","required":true},{"name":"email","label":"Email","type":"email","required":true},{"name":"phone","label":"Telefone","type":"phone","required":true}]'::jsonb, 'https://curso.kanaflix.com.br/checkout/10000004', true);
