// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwytxapogblcesvyxrzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3eXR4YXBvZ2JsY2Vzdnl4cnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMjQ3NjQsImV4cCI6MjA4NDYwMDc2NH0.voAfjTPEs5wFp8cqnyIYpn3EvKYqM6ABiTcnaB-INrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});